// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutricionApp.Persistencia;

namespace NutricionApp.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NutricionApp.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("NutricionApp.Dominio.SugerenciaCuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("SugerenciasCuidados");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("CaloriasConsumidas")
                        .HasColumnType("real");

                    b.Property<float>("Estatura")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Coach", b =>
                {
                    b.HasBaseType("NutricionApp.Dominio.Persona");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumeroCertificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Nutricionista", b =>
                {
                    b.HasBaseType("NutricionApp.Dominio.Persona");

                    b.Property<string>("TarjetaProfesional")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasDiscriminator().HasValue("Nutricionista");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Paciente", b =>
                {
                    b.HasBaseType("NutricionApp.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("int");

                    b.HasIndex("CoachId");

                    b.HasIndex("HistoriaId");

                    b.HasIndex("NutricionistaId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("NutricionApp.Dominio.SugerenciaCuidado", b =>
                {
                    b.HasOne("NutricionApp.Dominio.Paciente", null)
                        .WithMany("SugerenciasCuidados")
                        .HasForeignKey("PacienteId");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Valoracion", b =>
                {
                    b.HasOne("NutricionApp.Dominio.Paciente", null)
                        .WithMany("Valoraciones")
                        .HasForeignKey("PacienteId");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Paciente", b =>
                {
                    b.HasOne("NutricionApp.Dominio.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("NutricionApp.Dominio.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("HistoriaId");

                    b.HasOne("NutricionApp.Dominio.Nutricionista", "Nutricionista")
                        .WithMany()
                        .HasForeignKey("NutricionistaId");

                    b.Navigation("Coach");

                    b.Navigation("Historia");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutricionApp.Dominio.Paciente", b =>
                {
                    b.Navigation("SugerenciasCuidados");

                    b.Navigation("Valoraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
